version: "3.8"

services:
  sample-admin:
    build:
      context: ./sample-admin
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    depends_on:
      - gradle-build-admin

  gradle-build-admin:
    image: gradle:jdk17
    working_dir: /app
    volumes:
      - .:/app
    command: ./gradlew :sample-admin:build

  sample-apis-internal:
    build:
      context: ./sample-apis/internal-api
      dockerfile: Dockerfile  # 필요한 경우 경로에 맞는 Dockerfile 지정
    depends_on:
      - gradle-build-internal
    ports:
      - "8081:8080"  # internal-api 포트
  gradle-build-internal:
    image: gradle:jdk17
    working_dir: /app
    volumes:
      - .:/app
    command: ./gradlew :sample-apis:internal-api:build

  sample-apis-external:
    build:
      context: ./sample-apis/external-api
      dockerfile: Dockerfile  # 필요한 경우 경로에 맞는 Dockerfile 지정
    depends_on:
      - gradle-build-external
    ports:
      - "8082:8081"  # external-api 포트
  gradle-build-external:
    image: gradle:jdk17
    working_dir: /app
    volumes:
      - .:/app
    command: ./gradlew :sample-apis:external-api:build

